# Project:   macbash
# File:      .golangci.yml
# Purpose:   golangci-lint configuration
# Language:  YAML
#
# License:   Apache-2.0
# Copyright: (c) 2025 HyperSec Pty Ltd

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gocritic

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable:
      - shadow
  goimports:
    local-prefixes: github.com/hypersec-io/macbash
  misspell:
    locale: US
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance

issues:
  exclude-rules:
    # Test files can have some relaxed rules
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
